version: "3"

services:

  postgres:
    image: postgres:9
    restart: on-failure
    ports:
      - "7331:5432"
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - "./musicGenres/dump.tar.gz:/docker-entrypoint-initdb.d/dump.sql.gz"